#mysql数据库
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: debian-sys-maint
  password: 'vdntF6YJsbfojhRi'
spring:
  #服务名字，整合用
  application:
    name: mes-verification
fastjson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

